manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar  # for MCU RGB LED control
      url-base: https://github.com/caksoylar 
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-rgbled-widget  # for MCU RGB LED control
      remote: caksoylar
      revision: main
  self:
    path: config
